### ISSUE TITLE
Checkbox 'off' setting?

### ISSUE THREAD

**Issue by GlennovitS** [pebble/slate#10]
Hi

This might just be me who isn't that clever - but when I have a checkbox:

<div class="item-container">
      <div class="item-container-header">Other settings</div>
      <div class="item-container-content">
			<label class="item">
			  Animation
			  <input type="checkbox" class="item-toggle" name="key5" id="key5" <?php if($key5=="on"){ Echo "checked";} ?>>
			</label>
		</div>
    </div>

How do I get the opposite-of-on-value - like 'off'. Currently my settings was this when the submit button is clicked:

...
'animation': $("input[name=key5]").val()
...

But that is only returning on?

Hope you can help - with a cool framework!!

**Comment by GlennovitS** [comment]
Okay - I guess one just have to ask the question before one can answer it himself :-P after quite some time I found a solution. For those other than me who didn't figured it out from start, here is what I did:

...
var value5 = document.getElementById('key5').checked ? "1" : "0";
...
'animation': value5,
...

Its pretty simple actually :-)

Thanks again for the framework!

**Comment by konsumer** [comment]
You can also use `checked` attribute, directly: `var value5 = $("#key5").attr('checked') `

**Comment by orviwan** [comment]
Slate has been superseded by [Clay](https://github.com/pebble/clay).
