### ISSUE TITLE
Update ColorPicker when setting value with JS

### ISSUE THREAD

**Issue by hitormiss** [pebble/slate#14]
There needs to be some way for the chosen color on a ColorPicker to update when you set the value of the input with JS.

For example, if you have a field of radio buttons that let you choose between default configurations, there needs to a way for the ColorPicker to update to show the newly set color if it changes.

thanks!

**Comment by hitormiss** [comment]
I figured out how to solve my own question.  

It doesn't look like there's a way to trigger an automatic update when the value of the input is changed with Javascript, but you can manually trigger the ColorPicker to update.

The following needs to be added to the end of the **itemColor** function

```
$color.bind('change', function() {
		$valueDisplay.css('background-color', $color.val().replace(/^0x/, '#'));
});
```

After you change the value of a ColorPicker's input with Javascript (ex. loading a default configuration), you can use the following to update the ColorPicker.

```
$('.item-color').change();
```

The above would update all ColorPickers, but you can just as easily select one or more specific ones.

(I adapted this solution from https://github.com/laktek/really-simple-color-picker)

**Comment by orviwan** [comment]
Slate has been superseded by [Clay](https://github.com/pebble/clay).
