### ISSUE TITLE
ColorPicker does not trigger Change Event

### ISSUE THREAD

**Issue by hitormiss** [pebble/slate#24]
When you select a color using a ColorPicker, the script does not trigger a Change event on the ColorPicker input (because the element is hidden).

This is an issue, for example, if you want a displayed ConfigurationString to update with new settings after choosing a color.

The following needs to be updated in the itemColor function to fix this:

`$color.val(value.replace(/^0x/, '#')).trigger('change');`

This triggers the Change event when the value of the input is changed (upon selecting a color).

**Comment by orviwan** [comment]
Slate has been superseded by [Clay](https://github.com/pebble/clay).
