### ISSUE TITLE
Please, add a sample JavaScript for each input element

### ISSUE THREAD

**Issue by maxim-kukushkin** [pebble/slate#27]
The README file shows sample HTML for each kind of element. However, it lacks the JavaScript which can be used to collect the data on Submit. The video and code examples don't cover all kinds of elements.

For instance, it's completely unclear how to get the active Tab-Button.

Could you please, add just a single line of JavaScript under each kind of input component which shows how to get the input data from it?

**Comment by orviwan** [comment]
Slate has been superseded by [Clay](https://github.com/pebble/clay).
