### ISSUE TITLE
Requested URL not found on this server when trying to save settings

### ISSUE THREAD

**Issue by kaijday** [pebble/slate#29]
var options = {
          'user_id' : localStorage['user_id'],
          'screen_name' : localStorage['screen_name']
        } 

        console.log(options);

        document.body.innerHTML += "<div class='item-container'><div class='item-container-content'><div class='item'>You're authenticated and ready to go! :) Close settings to continue!</div></div></div>";

        document.body.innerHTML += "<div class='item-container'><div class='button-container'><input id='submit_button' type='button' class='item-button' value='SAVE'></div></div></div>";

        var submitButton = document.getElementById('submit_button');
        submitButton.addEventListener('click', function() {
          // Set the return URL depending on the runtime environment
          var return_to = getQueryParam('return_to', 'pebblejs://close#');
          document.location = return_to + encodeURIComponent(JSON.stringify(getConfigData()));
        });

**Comment by orviwan** [comment]
Slate has been superseded by [Clay](https://github.com/pebble/clay).
