### ISSUE TITLE
"Send" button at the page bottom of the template.html does not work

### ISSUE THREAD

**Issue by jensbocklage** [pebble/slate#3]
Using iPhone 6, iOS 8.4, Pebble Time.

I uploaded the dist folder to my webserver, used your template.html and changed the path to the dist folder in the html file:
http://config.qrwatch.de/template.html

I stripped down the template.html to only contain radio buttons and the send button:
http://config.qrwatch.de/v32.php

On both pages, the send button does not work on my iPhone (in the config-page of the watchface (pebble time app)) and Firefox browser (on my desktop PC).
When pressing the button, simply nothing happens.

**Comment by flashback2k14** [comment]
You must self implement this function. Look at the pebble developer getting started: 
http://developer.getpebble.com/getting-started/watchface-tutorial/part3/

**Comment by jensbocklage** [comment]
I'm not sure, what you mean.
I have this in my app to handle the config:

Pebble.addEventListener("showConfiguration",
  function(e) {
    Pebble.openURL("http://config.qrwatch.de/v32.php");
  }
);
Pebble.addEventListener("webviewclosed",
  function(e) {
    var configuration = JSON.parse(e.response);
    console.log(e.response);
    Pebble.sendAppMessage(configuration);
  }
);

**Comment by flashback2k14** [comment]
Sorry. Wrong tutorial. Please look at this:
https://ninedof.wordpress.com/2014/05/24/pebble-sdk-2-0-tutorial-9-app-configuration/

At the end you will See how to send back your options to the pebble. You must implement a click listner for the send button on your config.html or template.html.

<script>
  //Setup to allow easy adding more options later
  function saveOptions() {
    var invertSelect = document.getElementById("invert_select");
 
    var options = {
      "invert": invertSelect.options[invertSelect.selectedIndex].value
    }
     
    return options;
  };
 
  var submitButton = document.getElementById("save_button");
  submitButton.addEventListener("click", 
    function() {
      console.log("Submit");
 
      var options = saveOptions();
      var location = "pebblejs://close#" + encodeURIComponent(JSON.stringify(options));
       
      document.location = location;
    }, 
  false);
</script>

**Comment by jensbocklage** [comment]
I get the idea, but where is the code for sending back the data from the HTML file?

I think, there should be something like

var location = "pebblejs://close#" + encodeURIComponent(JSON.stringify(options));
document.location = location;

somewhere...
Or isn't this part of slate?

If not, I would like to see an example in the decumentation (I can provide this as soon as I have everything working ;) )

**Comment by flashback2k14** [comment]
I don't know how PHP works, but you could add this script tag in your HTML. This should work.

And yes, this is not part of slate. Slate style your elements.

```html

<script>
  //Setup to allow easy adding more options later
  function saveOptions() {
    var invertSelect = document.getElementById("invert_select");
 
    var options = {
      "invert": invertSelect.options[invertSelect.selectedIndex].value
    }
     
    return options;
  };
 
  var submitButton = document.getElementById("save_button");
  submitButton.addEventListener("click", 
    function() {
      console.log("Submit");
 
      var options = saveOptions();
      var location = "pebblejs://close#" + encodeURIComponent(JSON.stringify(options));
       
      document.location = location;
    }, 
  false);
</script>

```

**Comment by kirbyk** [comment]
Hey @jensbocklage, like @flashback2k14 said Slate only styles your elements. In the future we plan to make the serializing and deserializing of the settings much easier.

Until then @flashback2k14's example should be exactly what you need.

**Comment by jensbocklage** [comment]
OK. Got everything working.
Config -> App
and 
App -> Config.

Thanks for all your help.
@kirbyk Shall we all a code example to your repo is @flashback2k14 's example sufficient?

**Comment by kirbyk** [comment]
I think we're okay. This issue documents it for the future if people have questions.
