### ISSUE TITLE
How can we display a 'title' on the left side of a slider ?

### ISSUE THREAD

**Issue by gregoiresage** [pebble/slate#6]
I did that : 

```html
<label class="item item-subtitle-wrapper">
  Length
  <input type="range" class="item-slider" id="length" name="length" value="17" min="0" max="1000">
  <div class="item-input-wrapper item-slider-text">
    <input type="text" class="item-input" name="length" value="17">
  </div>
  <div class="item-subtitle">Between 0 and 100</div>
</label>
```

But the slider is displayed under the text input

![slate](https://cloud.githubusercontent.com/assets/4145305/9048787/252964b8-3a3c-11e5-995e-914845242aa4.png)

If I can display it just on top, it is okay for me too :-)

**Comment by orviwan** [comment]
Slate has been superseded by [Clay](https://github.com/pebble/clay).
